[package]
name = "intel8080_emu"
version = "0.1.0"
edition = "2021"
description = "Intel 8080 Emulator with Monitor ROM"
authors = ["Mike"]

[dependencies]
crossterm = "0.27"

[lib]
name = "intel8080_emu"
path = "src/lib.rs"

[[bin]]
name = "intel8080"
path = "src/main.rs"
